apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-limit-app
  namespace: default
  labels:
    app: connection-limit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection-limit-app
  template:
    metadata:
      labels:
        app: connection-limit-app
    spec:
      containers:
        - image: gcr.io/k8s-staging-gateway-api/echo-basic:v20231214-v1.0.0-140-gf544a46e
          imagePullPolicy: IfNotPresent
          name: connection-limit-app
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace